### ISSUE TITLE
Undefined variable $dropdown-link-hover-color

### ISSUE THREAD

**Issue by spectator** [ShPakvel/simple_navigation_renderers#2]
Hi there,

Thank you for your work on simple_navigation_renderers. I have recently started using it and have an issue during assets precompile.

``` shell
** Invoke assets:precompile (first_time)
** Execute assets:precompile
/Users/spectator/.rbenv/versions/2.1.0/bin/ruby /Users/spectator/.rbenv/versions/2.1.0/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets --trace
** Invoke assets:precompile:all (first_time)
** Invoke assets:cache:clean (first_time)
** Invoke assets:environment (first_time)
** Execute assets:environment
** Execute assets:cache:clean
** Execute assets:precompile:all
rake aborted!
Undefined variable: "$dropdown-link-hover-color".
  (in /Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/simple_navigation_renderers-0.0.3/vendor/assets/stylesheets/bootstrap2_dropdown_submenu.css.scss)
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/simple_navigation_renderers-0.0.3/vendor/assets/stylesheets/bootstrap2_dropdown_submenu.css.scss:4
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/script/variable.rb:49:in `_perform'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/script/node.rb:40:in `perform'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/perform.rb:298:in `visit_prop'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/perform.rb:320:in `visit_rule'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/base.rb:53:in `map'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/perform.rb:128:in `visit_root'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/base.rb:37:in `visit'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/perform.rb:100:in `visit'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/visitors/perform.rb:7:in `visit'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/tree/root_node.rb:20:in `render'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/engine.rb:315:in `_render'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-3.2.14/lib/sass/engine.rb:262:in `render'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sass-rails-3.2.6/lib/sass/rails/template_handlers.rb:106:in `evaluate'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sprockets-2.2.2/lib/sprockets/context.rb:193:in `block in evaluate'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sprockets-2.2.2/lib/sprockets/context.rb:190:in `each'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sprockets-2.2.2/lib/sprockets/context.rb:190:in `evaluate'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/processed_asset.rb:16:in `initialize'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/base.rb:18:in `new'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/base.rb:18:in `block in build_asset'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:270:in `circular_call_protection'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/base.rb:14:in `build_asset'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:93:in `block in build_asset'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sprockets-2.2.2/lib/sprockets/caching.rb:19:in `cache_asset'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:92:in `build_asset'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:169:in `find_asset'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/index.rb:14:in `find_asset'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/bundled_asset.rb:12:in `initialize'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/base.rb:22:in `new'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/base.rb:22:in `build_asset'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:93:in `block in build_asset'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sprockets-2.2.2/lib/sprockets/caching.rb:19:in `cache_asset'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:92:in `build_asset'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:169:in `find_asset'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/index.rb:14:in `find_asset'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/static_compiler.rb:41:in `block in compile'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:219:in `block in each_logical_path'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:206:in `block (2 levels) in each_file'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:196:in `each'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:196:in `each_entry'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:204:in `block in each_file'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:203:in `each'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:203:in `each_file'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:217:in `each_logical_path'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/sprockets_overrides/static_compiler.rb:29:in `compile'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/tasks/assets.rake:108:in `internal_precompile'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/tasks/assets.rake:115:in `block (3 levels) in <top (required)>'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:236:in `call'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:236:in `block in execute'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:231:in `each'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:231:in `execute'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:161:in `invoke'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:149:in `invoke_task'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:106:in `each'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:106:in `block in top_level'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:115:in `run_with_threads'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:100:in `top_level'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:78:in `block in run'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/bin/rake:33:in `<top (required)>'
/Users/spectator/.rbenv/versions/2.1.0/bin/rake:23:in `load'
/Users/spectator/.rbenv/versions/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => assets:precompile:all
rake aborted!
Command failed with status (1): [/Users/spectator/.rbenv/versions/2.1.0/bin...]
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/file_utils.rb:54:in `block in create_shell_runner'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/file_utils.rb:45:in `call'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/file_utils.rb:45:in `sh'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/file_utils_ext.rb:37:in `sh'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/file_utils.rb:82:in `ruby'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/file_utils_ext.rb:37:in `ruby'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/tasks/assets.rake:24:in `ruby_rake_task'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/tasks/assets.rake:33:in `invoke_or_reboot_rake_task'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/turbo-sprockets-rails3-0.3.11/lib/turbo-sprockets/tasks/assets.rake:50:in `block (2 levels) in <top (required)>'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:236:in `call'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:236:in `block in execute'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:231:in `each'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:231:in `execute'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:168:in `invoke_with_call_chain'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/task.rb:161:in `invoke'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:149:in `invoke_task'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:106:in `each'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:106:in `block in top_level'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:115:in `run_with_threads'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:100:in `top_level'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:78:in `block in run'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
/Users/spectator/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/rake-10.1.1/bin/rake:33:in `<top (required)>'
/Users/spectator/.rbenv/versions/2.1.0/bin/rake:23:in `load'
/Users/spectator/.rbenv/versions/2.1.0/bin/rake:23:in `<main>'
Tasks: TOP => assets:precompile
```

Related Gemfile entries

``` ruby
gem 'bootstrap-sass',     '3.1.1.0'

gem 'simple-navigation',  '3.11.0'
gem 'simple_navigation_renderers', '~> 0.0.3',
```

It works well in development mode, but assets precompile is probably trying to compile everything it can get its hands on even though I never explicitly required any overrides.

If I explicitly require one of those overrides, I'm getting the same error in development mode.

``` sass
//= require bootstrap
//= require bootstrap2_dropdown_submenu
```

Since I don't use overrides, my current workaround is

``` ruby
gem 'simple_navigation_renderers', '~> 0.0.3', require: false
```

``` ruby
require 'simple_navigation_renderers'

SimpleNavigation::Configuration.run do |navigation|
# ...
```

Am I missing something?

**Comment by ShPakvel** [comment]
Hi Yruy.

I think you have problem because of using `//= require bootstrap` format instead of `@import "bootstrap";` format. Because of this there is no possibility to use Bootstrap variables and mixins. This is not recommended way. Please use SASS's `@import` format.
Here is [chapter of the official documentation of `bootstrap-sass`](https://github.com/twbs/bootstrap-sass#sass) that tell about this.

Let me know if it helps you.

**Comment by spectator** [comment]
Sorry, I actually changed that to `import` but didn't update my original report.

I do use `@import 'bootstrap'`, not `//= require bootstrap`.

When I run assets precompile I get the error described above, but in development everything works fine.

If I explicitly require `bootstrap2_dropdown_submenu` in addition to bootstrap

``` sass
@import 'bootstrap'
@import 'bootstrap2_dropdown_submenu'
```

assets precompile still does not work the same way and in development I starting to get

``` shell
File to import not found or unreadable: bootstrap2_dropdown_submenu.
Load paths:
  Sass::Rails::Importer(/_omitted_/app/assets/stylesheets/admin/import_bootstrap.sass)
  /_omitted_/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/bootstrap-sass-3.1.1.0/vendor/assets/stylesheets
  (in /_omitted_/app/assets/stylesheets/admin/import_bootstrap.sass)
```

Workaround described above helps to deal with both issues.

**Comment by ShPakvel** [comment]
I cannot reproduce the same problem.
Could you please provide your stack (ruby, rails, so on)
And please provide your Gemfile, application.css.scss, import_bootstrap.sass and other you think important.

**Comment by spectator** [comment]
I created a sample app but couldn't reproduce this error, so it is somewhere in our app. I'll keep digging.

Thank you for looking into this!
